[package]
name = "topngx"
version = "0.1.0"
authors = ["Garrett Squire <github@garrettsquire.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
atty = "0.2"
env_logger = "0.7"
log = "0.4"
once_cell = "1.4"
regex = "1.3"
rusqlite = "0.23"
structopt = "0.3"
tabwriter = "1.2"
